### ISSUE TITLE
When and Q Reject

### ISSUE THREAD

**Issue by pcfreak30** [cujojs/when#431] opened 2015-02-25 15:48 UTC
I am using phbridge and when rejecting a nested Q promise (via reject() callback) the code logic goes to `node_modules/phridge/node_modules/when/lib/decorators/unhandledRejection.js:80` and ending the app instead of bubbling up the rejection. This causes me to have to set an error flag in a parent scope and reject elsewhere based on that..

When.js library version 3.7.2 is running 

Thanks.

**Comment by briancavalier** [comment] 2015-02-26 03:20
Hey @pcfreak30.  I'm not sure what phbridge is, can you help me out with a link or more info?

Do you have a runnable test case you can post?  Or at least enough of a representative example so I can understand the situation?  Thanks!

Also, I figure node is probably halting with a stack trace.  Could you post the stack trace as well?

The only way the code can end up at that line, is if someone is calling `done` at the end of a when.js promise chain, and that chain rejects without the rejection ever being handled.  That behavior is the []intended behavior of `done`](https://github.com/cujojs/when/blob/master/docs/api.md#promisedone).  However, if you can provide a test case, we can verify that it's all working as intended, or if there's a bug.

**Comment by briancavalier** [comment] 2015-03-30 01:36
Ping @pcfreak30.  Can you provide more info, or shall we close this?

**Comment by briancavalier** [comment] 2015-04-03 00:58
@pcfreak30 Since it's been a while, I'm closing this.  If you can provide an update and/or more info, please reopen.

**Closed by briancavalier** 2015-04-03 00:58 UTC
